# Conda environment file for captest v0.5*
# Package versions match Anaconda Distribution as of 4/28/19 for python 3.7
# To create a conda environment using this file:
# conda env create -f captest_env.yml
name: captest_env_05_test
dependencies:
- python=3.7*
- bokeh=1.0.4
- pandas=0.24.2
- numpy=1.16.2
- python-dateutil=2.8.0
- statsmodels=0.9.0
- scipy=1.2.1
- scikit-learn=0.20.3
- matplotlib=3.0.3
- holoviews=1.11.3
- notebook*
- ipython*
- pip
- pip:
    - tables
    - pvlib
    - captest
