# To create a conda environment using this file:
# conda env create -f captest_env.yml
name: captest09
channels:
- defaults
- conda-forge
- pyviz
dependencies:
- holoviz
- matplotlib
- numpy
- pandas>=1*
- python>=3.7*
- python-dateutil
- statsmodels
- scikit-learn
- scipy=1.2.1
- ipython
- jupyterlab
- notebook
- pvcaptest
- nodejs # for jupyterlab pyviz extension
