name: pytest

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  test:
    strategy:
      fail-fast: false  # don't cancel other matrix jobs when one fails
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Get tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]

      - name: Run tests
        run: |
          pytest --cov-report=xml --cov=captest tests/

      # - name: Upload coverage to Codecov
      #   if: matrix.python-version == 3.7 && matrix.suffix == '' && matrix.os == 'ubuntu-latest' && matrix.environment-type == 'conda'
      #   uses: codecov/codecov-action@v3
      #   with:
      #     fail_ci_if_error: true
      #     verbose: true
      #     flags: core  # flags are configured in codecov.yml
